title: Code Switching
description: Code Switching Workshop
theme: jekyll-theme-architect
github:
  owner_name: Jason
  wi_url: Code-Switching/workshopinformation/wi.html
  oc_url: Code-Switching/organizingcommittee/oc.html
